{"ray": {"sid": "80e127e7cf0640f081945b250d7c6c06", "uid": null, "qid": "c49226c7ffe949dd815e04ecb0d402f6", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [c49226c7ffe949dd815e04ecb0d402f6]\nTraceback (most recent call last):\n  File \"/home/nouman/Documents/openfabric-ai-software-engineer/openfabric-ai-software-engineer/venv/lib/python3.10/site-packages/openfabric_pysdk/app/worker.py\", line 90, in process\n    output = execution_callback_function(data, ray, self.state)\n  File \"/home/nouman/Documents/openfabric-ai-software-engineer/openfabric-ai-software-engineer/main.py\", line 53, in execute\n    bot_response = generate_response(query=text)\n  File \"/home/nouman/Documents/openfabric-ai-software-engineer/openfabric-ai-software-engineer/utils.py\", line 41, in generate_response\n    llm = ChatOpenAI()\n  File \"/home/nouman/Documents/openfabric-ai-software-engineer/openfabric-ai-software-engineer/venv/lib/python3.10/site-packages/langchain_core/load/serializable.py\", line 107, in __init__\n    super().__init__(**kwargs)\n  File \"/home/nouman/Documents/openfabric-ai-software-engineer/openfabric-ai-software-engineer/venv/lib/python3.10/site-packages/pydantic/v1/main.py\", line 341, in __init__\n    raise validation_error\npydantic.v1.error_wrappers.ValidationError: 1 validation error for ChatOpenAI\n__root__\n  Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass `openai_api_key` as a named parameter. (type=value_error)\n", "created_at": "2024-01-15T17:25:48.004328"}], "status": "FAILED", "created_at": "2024-01-15T17:25:47.871911", "updated_at": "2024-01-15T17:25:48.005262", "finished": true}, "in": {"text": ["what is science?"]}, "out": {}}